import { Link, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '../lib/supabase';

const usd = (value: number | null) => `$${Number(value ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
type Customer = { id: string; customer_number: string; first_name: string; last_name: string | null; phone: string; address: string | null };
type Sale = { id: string; sale_number: string; sale_date: string; total_amount: number; amount_paid: number; balance_due: number; payment_status: string };
type Installation = { id: string; job_number: string; status: string; scheduled_date: string | null; serial_numbers: { serial_number: string; products: { description: string | null } | null } | null };
type Warranty = { id: string; warranty_number: string; status: string; expiry_date: string | null; serial_numbers: { serial_number: string } | null };

export function Customer360() {
  const { customerId } = useParams<{ customerId: string }>();
  const customerQuery = useQuery({ queryKey: ['customer', customerId], enabled: Boolean(customerId), queryFn: async () => { const { data, error } = await supabase.from('customers').select('*').eq('id', customerId!).single(); if (error) throw error; return data as unknown as Customer; } });
  const salesQuery = useQuery({ queryKey: ['customer_sales', customerId], enabled: Boolean(customerId), queryFn: async () => { const { data, error } = await supabase.from('sales').select('*').eq('customer_id', customerId!).order('sale_date', { ascending: false }); if (error) throw error; return (data ?? []) as unknown as Sale[]; } });
  const installsQuery = useQuery({ queryKey: ['customer_installs', customerId], enabled: Boolean(customerId), queryFn: async () => { const { data, error } = await supabase.from('installations').select('*, serial_numbers(*, products(*))').eq('customer_id', customerId!); if (error) throw error; return (data ?? []) as unknown as Installation[]; } });
  const warrantiesQuery = useQuery({ queryKey: ['customer_warranties', customerId], enabled: Boolean(customerId), queryFn: async () => { const { data, error } = await supabase.from('warranties').select('*, serial_numbers(*)').eq('customer_id', customerId!); if (error) throw error; return (data ?? []) as unknown as Warranty[]; } });
  if (customerQuery.isLoading) return <div className="p-10 text-center text-slate-400">Loading customer...</div>;
  if (customerQuery.error || !customerQuery.data) return <div className="p-10 text-center text-red-400">Customer not found.</div>;
  const customer = customerQuery.data; const sales = salesQuery.data ?? []; const installs = installsQuery.data ?? []; const warranties = warrantiesQuery.data ?? [];
  return <div className="mx-auto max-w-4xl space-y-5"><Link to="/customers" className="text-sm text-slate-400 hover:text-slate-200">Back to customers</Link><header><h1 className="text-2xl font-bold text-white">{customer.first_name} {customer.last_name ?? ''}</h1><p className="text-sm text-slate-400">{customer.customer_number} · {customer.phone} · {customer.address ?? 'No address'}</p></header><div className="grid grid-cols-2 gap-4 md:grid-cols-5"><Stat label="Lifetime sales" value={sales.length} /><Stat label="Total paid" value={usd(sales.reduce((sum, sale) => sum + Number(sale.amount_paid), 0))} accent /><Stat label="Outstanding" value={usd(sales.reduce((sum, sale) => sum + Number(sale.balance_due), 0))} /><Stat label="Installed units" value={installs.filter(install => install.status === 'COMPLETED').length} /><Stat label="Active warranties" value={warranties.filter(warranty => warranty.status === 'ACTIVE').length} /></div><Panel title="Sales history">{sales.length === 0 ? <Empty text="No sales yet." /> : sales.map(sale => <Link key={sale.id} to={`/sales/${sale.id}`} className="flex items-center justify-between border-b border-slate-800 py-3 last:border-0"><span className="text-slate-300">{sale.sale_number}<small className="ml-2 text-slate-500">{new Date(sale.sale_date).toLocaleDateString()}</small></span><span className="text-right"><strong className="block text-white">{usd(sale.total_amount)}</strong><small className="text-slate-500">{sale.payment_status.replace(/_/g, ' ')}</small></span></Link>)}</Panel><Panel title="Installed assets">{installs.length === 0 ? <Empty text="No installations yet." /> : installs.map(install => <div key={install.id} className="flex justify-between border-b border-slate-800 py-3 last:border-0"><span className="font-mono text-amber-400">{install.serial_numbers?.serial_number ?? '-'}<small className="ml-2 font-sans text-slate-400">{install.serial_numbers?.products?.description ?? ''}</small></span><span className="text-xs text-slate-500">{install.status.replace(/_/g, ' ')}</span></div>)}</Panel><Panel title="Warranties">{warranties.length === 0 ? <Empty text="No warranties." /> : warranties.map(warranty => <div key={warranty.id} className="flex justify-between border-b border-slate-800 py-3 last:border-0"><span className="font-mono text-amber-400">{warranty.warranty_number} · {warranty.serial_numbers?.serial_number ?? '-'}</span><span className="text-xs text-slate-400">Expires {warranty.expiry_date ?? '-'} · {warranty.status}</span></div>)}</Panel></div>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-400">{title}</h2>{children}</section>; }
function Stat({ label, value, accent = false }: { label: string; value: string | number; accent?: boolean }) { return <div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs uppercase tracking-wide text-slate-500">{label}</div><div className={`mt-1 text-xl font-bold ${accent ? 'text-amber-400' : 'text-white'}`}>{value}</div></div>; }
function Empty({ text }: { text: string }) { return <p className="text-sm text-slate-500">{text}</p>; }
