import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { supabase } from '../lib/supabase';
import { createCustomer } from '../lib/rpc';

const schema = z.object({ firstName: z.string().min(1, 'Required'), lastName: z.string().optional(), phone: z.string().min(1, 'Required'), email: z.string().optional(), address: z.string().optional(), city: z.string().optional(), referralSource: z.string().optional() });
type CustomerForm = z.infer<typeof schema>;
type Customer = { id: string; customer_number: string; first_name: string; last_name: string | null; phone: string; email: string | null; address: string | null; city: string | null };

export function Customers() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [params] = useSearchParams(); const [showNew, setShowNew] = useState(params.get('new') === '1'); const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false);
  const query = useQuery({ queryKey: ['customers'], queryFn: async () => { const { data, error } = await supabase.from('customers').select('*').eq('status', 'ACTIVE').order('first_name'); if (error) throw error; return (data ?? []) as unknown as Customer[]; } });
  const form = useForm<CustomerForm>({ resolver: zodResolver(schema), defaultValues: { firstName: '', lastName: '', phone: '', email: '', address: '', city: 'Harare', referralSource: '' } });
  const list = (query.data ?? []).filter(customer => `${customer.first_name} ${customer.last_name ?? ''} ${customer.phone} ${customer.customer_number}`.toLowerCase().includes(search.toLowerCase()));
  async function onCreate(data: CustomerForm) { setBusy(true); try { await createCustomer({ first_name: data.firstName, last_name: data.lastName || undefined, phone: data.phone, email: data.email || undefined, address: data.address || undefined, city: data.city || 'Harare', referral_source: data.referralSource || undefined }); await queryClient.invalidateQueries({ queryKey: ['customers'] }); setShowNew(false); form.reset(); if (params.get('new') === '1') navigate('/sales/new'); } catch (error: unknown) { alert(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  if (query.isLoading) return <div className="p-10 text-center text-slate-400">Loading customers...</div>;
  if (query.error) return <div className="p-10 text-center text-red-400">Could not load customers.</div>;
  return <div className="mx-auto max-w-5xl space-y-5"><div className="flex items-center justify-between"><h1 className="text-2xl font-bold text-white">Customers</h1><button onClick={() => setShowNew(true)} className="rounded-md bg-amber-500 px-3 py-2 text-xs font-semibold text-slate-900">New Customer</button></div><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name, phone, or customer number" className="w-full max-w-sm rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" /><div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-800 text-xs uppercase text-slate-500"><th className="px-5 py-3">Customer</th><th>Number</th><th>Phone</th><th>Location</th></tr></thead><tbody>{list.map(customer => <tr key={customer.id} onClick={() => navigate(`/customers/${customer.id}`)} className="cursor-pointer border-b border-slate-800 last:border-0 hover:bg-slate-800"><td className="px-5 py-3 font-medium text-slate-200">{customer.first_name} {customer.last_name ?? ''}</td><td className="font-mono text-amber-400">{customer.customer_number}</td><td className="text-slate-300">{customer.phone}</td><td className="text-slate-400">{customer.city ?? 'Harare'}</td></tr>)}</tbody></table>{list.length === 0 && <p className="p-5 text-sm text-slate-500">No customers match.</p>}</div>{showNew && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><form onSubmit={form.handleSubmit(onCreate)} className="w-full max-w-md space-y-3 rounded-xl bg-white p-6"><h2 className="text-lg font-semibold text-slate-900">New Customer</h2><div className="grid grid-cols-2 gap-3"><Field label="First name" error={form.formState.errors.firstName?.message}><input {...form.register('firstName')} className="input" /></Field><Field label="Last name"><input {...form.register('lastName')} className="input" /></Field><Field label="Phone" error={form.formState.errors.phone?.message}><input {...form.register('phone')} className="input" placeholder="077..." /></Field><Field label="Email"><input {...form.register('email')} className="input" /></Field><Field label="Address" wide><input {...form.register('address')} className="input" /></Field><Field label="Referral source" wide><input {...form.register('referralSource')} className="input" /></Field></div><div className="flex gap-2"><button disabled={busy} type="submit" className="flex-1 rounded bg-slate-900 py-2 text-sm font-semibold text-white">{busy ? 'Creating...' : 'Create'}</button><button type="button" onClick={() => setShowNew(false)} className="rounded border px-4 py-2 text-sm text-slate-700">Cancel</button></div></form></div>}</div>;
}
function Field({ label, error, wide = false, children }: { label: string; error?: string; wide?: boolean; children: React.ReactNode }) { return <label className={wide ? 'col-span-2' : ''}><span className="mb-1 block text-sm text-slate-600">{label}</span>{children}{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>; }
