import { useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '../lib/supabase';
import { adjustSerialStatus, receiveStock, setSerialQc } from '../lib/rpc';
import { useRole } from '../hooks/useRole';

const statusTone: Record<string, string> = {
  AVAILABLE: 'bg-emerald-500/10 text-emerald-300', RESERVED: 'bg-blue-500/10 text-blue-300',
  ALLOCATED: 'bg-indigo-500/10 text-indigo-300', INSTALLED: 'bg-slate-800 text-slate-400',
  DAMAGED: 'bg-red-500/10 text-red-300', SCRAPPED: 'bg-red-500/10 text-red-300', RETURNED: 'bg-amber-500/10 text-amber-300',
};

type Stock = { product_id: string; sku: string; name: string; selling_price: number; available_units: number; reserved_units: number; installed_units: number; days_of_stock_remaining: number | null; restock_status: string };
type Product = { id: string; sku: string; name: string; description: string | null; requires_serial: boolean };
type Serial = { id: string; serial_number: string; status: string; received_date: string | null; qc_status: string | null };

export function Inventory() {
  const queryClient = useQueryClient();
  const { isOwner } = useRole();
  const [selected, setSelected] = useState<string | null>(null);
  const [showReceive, setShowReceive] = useState(false);
  const stockQuery = useQuery({ queryKey: ['v_stock_dashboard'], queryFn: async () => { const { data, error } = await supabase.from('v_stock_dashboard').select('*'); if (error) throw error; return (data ?? []) as unknown as Stock[]; } });
  const productsQuery = useQuery({ queryKey: ['products'], queryFn: async () => { const { data, error } = await supabase.from('products').select('*').eq('active', true).order('sku'); if (error) throw error; return (data ?? []) as unknown as Product[]; } });
  if (stockQuery.isLoading) return <div className="p-10 text-center text-slate-400">Loading inventory...</div>;
  if (stockQuery.error) return <div className="p-10 text-center text-red-400">Could not load inventory.</div>;
  const product = productsQuery.data?.find(item => item.sku === selected);
  return <div className="mx-auto max-w-6xl space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">Inventory</h1><p className="text-xs text-slate-500">Serialized unit tracking and restock automation</p></div>{isOwner && <button onClick={() => setShowReceive(true)} className="rounded-lg bg-amber-500 px-4 py-2 text-xs font-semibold text-slate-900">Receive Stock</button>}</div><section className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900 p-5"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-500"><th className="px-3 py-2">SKU</th><th className="px-3 py-2">Product</th><th className="px-3 py-2">Price</th><th className="px-3 py-2 text-right">Available</th><th className="px-3 py-2 text-right">Reserved</th><th className="px-3 py-2 text-right">Installed</th><th className="px-3 py-2 text-right">Days</th><th className="px-3 py-2">Status</th></tr></thead><tbody>{stockQuery.data?.map(row => <tr key={row.sku} onClick={() => setSelected(selected === row.sku ? null : row.sku)} className="cursor-pointer border-b border-slate-800/60 hover:bg-slate-800"><td className="px-3 py-3 font-mono font-bold text-slate-200">{row.sku}</td><td className="px-3 py-3 text-slate-300">{row.name}</td><td className="px-3 py-3 text-slate-300">${Number(row.selling_price).toFixed(2)}</td><td className="px-3 py-3 text-right text-white">{row.available_units}</td><td className="px-3 py-3 text-right text-slate-400">{row.reserved_units}</td><td className="px-3 py-3 text-right text-slate-400">{row.installed_units}</td><td className="px-3 py-3 text-right text-slate-400">{row.days_of_stock_remaining ?? '-'}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${row.restock_status === 'REORDER_NOW' ? 'bg-red-500/10 text-red-300' : row.restock_status === 'NO_SALES_YET' ? 'bg-slate-800 text-slate-500' : 'bg-emerald-500/10 text-emerald-300'}`}>{row.restock_status.replace(/_/g, ' ')}</span></td></tr>)}</tbody></table></section>{product && <SerialDrilldown product={product} isOwner={isOwner} />}{showReceive && <ReceiveModal products={(productsQuery.data ?? []).filter(item => item.requires_serial)} onClose={() => setShowReceive(false)} onDone={() => { setShowReceive(false); queryClient.invalidateQueries(); }} />}</div>;
}

function SerialDrilldown({ product, isOwner }: { product: Product; isOwner: boolean }) {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ['serials', product.id], queryFn: async () => { const { data, error } = await supabase.from('serial_numbers').select('*').eq('product_id', product.id).order('serial_number'); if (error) throw error; return (data ?? []) as unknown as Serial[]; } });
  async function qc(serialId: string, status: string) { try { await setSerialQc(serialId, status); await queryClient.invalidateQueries({ queryKey: ['serials', product.id] }); } catch (error: unknown) { alert(error instanceof Error ? error.message : String(error)); } }
  async function photo(serialId: string, file: File) { const path = `receiving/${product.sku}/${Date.now()}-${file.name}`; const upload = await supabase.storage.from('documents').upload(path, file); if (upload.error) return alert(upload.error.message); try { await setSerialQc(serialId, 'PASS', path); await queryClient.invalidateQueries({ queryKey: ['serials', product.id] }); } catch (error: unknown) { alert(error instanceof Error ? error.message : String(error)); } }
  async function adjust(serialId: string, status: string) { const reason = prompt(`Reason for marking ${status}:`); if (!reason) return; try { await adjustSerialStatus(serialId, status, reason); await queryClient.invalidateQueries({ queryKey: ['serials', product.id] }); } catch (error: unknown) { alert(error instanceof Error ? error.message : String(error)); } }
  return <section className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="mb-3 text-sm font-semibold uppercase text-slate-400">Serials - {product.sku}</h2><div className="space-y-2">{query.data?.map(serial => <div key={serial.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 pb-2 text-sm"><div><span className="font-mono font-medium text-amber-400">{serial.serial_number}</span><span className={`ml-2 rounded-full px-2 py-1 text-[10px] font-semibold ${statusTone[serial.status] ?? 'bg-slate-800 text-slate-400'}`}>{serial.status}</span>{serial.qc_status && <span className="ml-2 text-xs text-slate-500">QC: {serial.qc_status}</span>}</div>{isOwner && serial.status === 'AVAILABLE' && <div className="flex gap-2 text-xs"><button onClick={() => qc(serial.id, 'PASS')} className="rounded bg-emerald-500/10 px-2 py-1 text-emerald-300">Pass</button><button onClick={() => qc(serial.id, 'FAIL')} className="rounded bg-red-500/10 px-2 py-1 text-red-300">Fail</button><PhotoButton onFile={file => photo(serial.id, file)} /><button onClick={() => adjust(serial.id, 'DAMAGED')} className="rounded bg-slate-800 px-2 py-1 text-slate-300">Damage</button></div>}</div>)}</div></section>;
}

function PhotoButton({ onFile }: { onFile: (file: File) => void }) { const input = useRef<HTMLInputElement>(null); return <><input ref={input} type="file" accept="image/*" capture="environment" className="hidden" onChange={event => { const file = event.target.files?.[0]; if (file) onFile(file); event.target.value = ''; }} /><button type="button" onClick={() => input.current?.click()} className="rounded bg-blue-500/10 px-2 py-1 text-blue-300">Photo</button></>; }

function ReceiveModal({ products, onClose, onDone }: { products: Product[]; onClose: () => void; onDone: () => void }) { const [productId, setProductId] = useState(''); const [serialText, setSerialText] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [busy, setBusy] = useState(false); async function submit() { const serials = serialText.split(/[\n,]+/).map(value => value.trim()).filter(Boolean); if (!productId || serials.length === 0) return alert('Choose a product and enter serials.'); setBusy(true); try { await receiveStock({ product_id: productId, serial_numbers: serials, received_date: date }); onDone(); } catch (error: unknown) { alert(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } } return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md space-y-4 rounded-xl bg-white p-6"><h2 className="text-lg font-semibold text-slate-900">Receive Stock</h2><select value={productId} onChange={event => setProductId(event.target.value)} className="w-full rounded border p-2 text-sm text-slate-900"><option value="">Select product</option>{products.map(product => <option key={product.id} value={product.id}>{product.sku} - {product.description ?? product.name}</option>)}</select><textarea rows={5} value={serialText} onChange={event => setSerialText(event.target.value)} placeholder="One serial per line" className="w-full rounded border p-2 font-mono text-sm text-slate-900" /><input type="date" value={date} onChange={event => setDate(event.target.value)} className="w-full rounded border p-2 text-sm text-slate-900" /><div className="flex gap-2"><button onClick={submit} disabled={busy} className="flex-1 rounded bg-slate-900 py-2 text-sm text-white">{busy ? 'Receiving...' : 'Receive'}</button><button onClick={onClose} className="rounded border px-4 py-2 text-sm text-slate-700">Cancel</button></div></div></div>; }
